# Generated by Django 3.1.14 on 2025-03-25 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название на японском')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_evolution', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField(verbose_name='Широта')),
                ('Lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(default=datetime.datetime(2025, 3, 25, 22, 18, 5, 168444), verbose_name='Начало')),
                ('disappeared_at', models.DateTimeField(default=datetime.datetime(2025, 4, 1, 22, 18, 5, 168471), verbose_name='Конец')),
                ('Level', models.IntegerField(default=20, verbose_name='Уровень')),
                ('Health', models.IntegerField(default=20, verbose_name='Здоровье')),
                ('Damage', models.IntegerField(default=20, verbose_name='Урон')),
                ('Defence', models.IntegerField(default=20, verbose_name='Защита')),
                ('Endurance', models.IntegerField(default=20, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
