# Generated by Django 3.1.14 on 2025-03-28 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название на японском')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Картинка')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 28, 20, 39, 26, 688727), null=True, verbose_name='Дата появления покемона')),
                ('disappeared_at', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 4, 20, 39, 26, 688754), null=True, verbose_name='Дата исчезновения покемона')),
                ('level', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='Уровень')),
                ('health', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='Здоровье')),
                ('damage', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='Урон')),
                ('defence', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='Защита')),
                ('endurance', models.PositiveSmallIntegerField(blank=True, default=20, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
