# Generated by Django 3.1.14 on 2025-03-26 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20250327_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 27, 2, 33, 5, 388857), null=True, verbose_name='Дата появления покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 3, 2, 33, 5, 388884), null=True, verbose_name='Дата исчезновения покемона'),
        ),
    ]
